# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('series_in_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_city', to='meguriApp.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='city_in_prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_featured', to='meguriApp.prefecture'),
        ),
    ]
