# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meguriApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_in_prefecture',
        ),
        migrations.RemoveField(
            model_name='series',
            name='series_in_city',
        ),
    ]
