# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meguriApp', '0002_auto_20191022_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_in_prefecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefecture_city', to='meguriApp.prefecture'),
        ),
        migrations.AddField(
            model_name='city',
            name='series_featured_in_city',
            field=models.ManyToManyField(null=True, related_name='series_in_city', to='meguriApp.series'),
        ),
    ]
