# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meguriApp', '0003_auto_20191022_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
