# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meguriApp', '0004_series_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='city',
            field=models.CharField(default='Tokyo', max_length=255),
            preserve_default=False,
        ),
    ]
