# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meguriApp', '0005_series_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_in_prefecture',
        ),
        migrations.RemoveField(
            model_name='city',
            name='series_featured_in_city',
        ),
        migrations.RemoveField(
            model_name='series',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='series',
            field=models.ManyToManyField(related_name='city', to='meguriApp.Series'),
        ),
        migrations.DeleteModel(
            name='prefecture',
        ),
    ]
