# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meguriApp', '0009_auto_20191023_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='series',
            field=models.ManyToManyField(related_name='city', to='meguriApp.Series'),
        ),
        migrations.AlterField(
            model_name='location',
            name='series',
            field=models.ManyToManyField(related_name='locations', to='meguriApp.Series'),
        ),
    ]
