# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meguriApp', '0011_auto_20191024_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='series',
            field=models.ManyToManyField(related_name='city', to='meguriApp.Series'),
        ),
        migrations.AlterField(
            model_name='location',
            name='series',
            field=models.ManyToManyField(related_name='locations', to='meguriApp.Series'),
        ),
    ]
